(() => {
  const D = window.EDUCATION_CONTENT;
  const app = document.getElementById('educationApp');
  if (!app || !D) return;
  const icon = (name) => { const p={home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z',tag:'M4 4h7l9 9-7 7-9-9z',chart:'M4 20V10m6 10V4m6 16v-7m4 7H2',file:'M6 2h9l5 5v15H6zM14 2v6h6',shield:'M12 2l8 3v6c0 5-3.4 9-8 11-4.6-2-8-6-8-11V5z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8m13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',map:'M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15m6-12v15'}; return `<svg class="edu-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${p[name]||p.file}"/></svg>`; };
  const nav=[['rutas','Rutas'],['compra','Compra'],['venta','Venta'],['inversion','Inversión'],['documentos','Documentos'],['diccionario','Diccionario'],['guias','Guías'],['preguntas','Preguntas']];
  app.innerHTML=`
    <section class="edu-trust" aria-label="Beneficios"><div class="container edu-trust-grid">${[["map",'Contenido enfocado en Nicaragua'],['home','Orientación para comprar y vender'],['shield','Principios legales y comerciales'],['users','Acompañamiento inmobiliario']].map(x=>`<div>${icon(x[0])}<span>${x[1]}</span></div>`).join('')}</div></section>
    <nav class="edu-local-nav" aria-label="Contenido educativo"><div class="container">${nav.map(n=>`<a href="#${n[0]}">${n[1]}</a>`).join('')}</div></nav>
    <section class="edu-section container" id="rutas"><div class="edu-heading"><p class="edu-eyebrow">Aprendizaje a tu medida</p><h2>¿Qué quieres aprender?</h2><p>Selecciona un objetivo para explorar contenidos organizados y accionables.</p></div><div class="edu-paths" role="tablist" aria-label="Rutas de aprendizaje">${D.paths.map((p,i)=>`<button class="edu-path ${i?'':'is-active'}" role="tab" aria-selected="${!i}" aria-controls="path-panel" data-path="${p.id}">${icon(p.icon)}<span class="edu-path-state">${i?'Seleccionar':'Ruta activa'}</span><strong>${p.title}</strong><small>${p.description}</small><b>${p.modules.length} temas</b><em>Explorar ruta</em></button>`).join('')}</div><div id="path-panel" class="edu-path-panel" role="tabpanel" tabindex="0"></div></section>
    <section class="edu-section edu-tint" id="compra"><div class="container"><div class="edu-heading"><p class="edu-eyebrow">Proceso de compra</p><h2>Avanza paso a paso, no por impulso</h2></div><div class="edu-journey" data-journey="buying"></div></div></section>
    <section class="edu-section container" id="venta"><div class="edu-heading"><p class="edu-eyebrow">Proceso de venta</p><h2>Prepara una salida al mercado con criterio</h2></div><div class="edu-journey" data-journey="selling"></div><div class="edu-check-card"><div><p class="edu-eyebrow">Diagnóstico local</p><h3>¿Está tu propiedad lista para venderse?</h3><p id="checkProgress" aria-live="polite">0 de 6 pasos preparados</p><div class="edu-progress"><span></span></div></div><div class="edu-checklist">${D.checklist.map((x,i)=>`<label><input type="checkbox" data-check="${i}"><span>${x}</span></label>`).join('')}</div></div></section>
    <section class="edu-section edu-dark-panel" id="inversion"><div class="container"><div class="edu-heading"><p class="edu-eyebrow">Análisis responsable</p><h2>Inversión inmobiliaria sin promesas irreales</h2><p>Comprende cómo ubicación, plusvalía, liquidez, demanda, riesgo y horizonte se relacionan.</p></div><div class="edu-concepts">${D.paths[2].modules.map(x=>`<span>${x}</span>`).join('')}</div><div class="edu-calculator"><div><h3>Ejemplo orientativo de rentabilidad</h3><p>No representa asesoría financiera y no guarda información.</p><form id="calculator" novalidate><label>Moneda<select name="currency"><option value="USD">USD — dólares</option><option value="NIO">NIO — córdobas</option></select></label><label>Precio de compra<input name="price" type="number" min="0" step="0.01" inputmode="decimal" required></label><label>Ingreso mensual estimado<input name="income" type="number" min="0" step="0.01" inputmode="decimal" required></label><label>Gastos anuales estimados<input name="expenses" type="number" min="0" step="0.01" inputmode="decimal" required></label><button class="edu-btn edu-btn-primary" type="submit">Calcular estimación</button><p class="edu-form-error" id="calcError" role="alert"></p></form></div><div class="edu-results" id="calcResults" aria-live="polite"><p>Completa los campos para ver el ejemplo.</p></div></div><p class="edu-note">Los resultados de una inversión dependen de la ubicación, condiciones del mercado, costos, administración y características particulares de cada propiedad.</p></div></section>
    <section class="edu-section container" id="documentos"><div class="edu-heading"><p class="edu-eyebrow">Documentos y procesos en Nicaragua</p><h2>Una ruta general para ordenar la operación</h2></div><ol class="edu-process">${D.paths[3].modules.map((x,i)=>`<li><span>${i+1}</span><strong>${x}</strong></li>`).join('')}</ol><div class="edu-document-grid">${D.documents.map(x=>`<span>${icon('file')}${x}</span>`).join('')}</div><p class="edu-legal">Los requisitos pueden variar según el tipo de propiedad, municipio, antecedentes registrales y características de la operación. La documentación debe revisarse con profesionales competentes antes de firmar o realizar pagos.</p></section>
    <section class="edu-section edu-tint" id="diccionario"><div class="container"><div class="edu-heading"><p class="edu-eyebrow">Conceptos claros</p><h2>Diccionario inmobiliario</h2></div><div class="edu-gloss-controls"><label><span>Buscar un concepto</span><input id="glossSearch" type="search" placeholder="Ej. plusvalía, avalúo…"></label><div id="letterFilter" aria-label="Filtrar por inicial"><button class="is-active" data-letter="all">Todos</button>${[...new Set(D.glossary.map(x=>x.term[0]))].map(l=>`<button data-letter="${l}">${l}</button>`).join('')}</div></div><div class="edu-glossary" id="glossary"></div><p class="edu-empty" id="glossEmpty" hidden>No encontramos conceptos con esos criterios.</p></div></section>
    <section class="edu-section container"><div class="edu-heading"><p class="edu-eyebrow">Criterio sobre creencias comunes</p><h2>Mitos y realidades del mercado inmobiliario</h2></div><div class="edu-myths">${D.myths.map((m,i)=>`<article><span>Mito ${i+1}</span><h3>${m[0]}</h3><button aria-expanded="false">Ver realidad</button><div hidden><strong>Realidad</strong><p>${m[1]}</p></div></article>`).join('')}</div></section>
    <section class="edu-section edu-tint"><div class="container"><div class="edu-heading"><p class="edu-eyebrow">Evita puntos ciegos</p><h2>Errores comunes por perfil</h2></div><div class="edu-segments" role="tablist">${Object.keys(D.mistakes).map((x,i)=>`<button role="tab" aria-selected="${!i}" class="${i?'':'is-active'}" data-profile="${x}">${x}</button>`).join('')}</div><ul class="edu-mistakes" id="mistakes"></ul></div></section>
    <section class="edu-section container" id="guias"><div class="edu-heading"><p class="edu-eyebrow">Biblioteca esencial</p><h2>Guías prácticas</h2></div><div class="edu-guides">${D.guides.map(g=>`<article><span>${g.category}</span><h3>${g.title}</h3><p>${g.description}</p><small>${g.time} de lectura</small><button class="edu-text-btn" data-guide="${g.id}">Leer guía</button></article>`).join('')}</div></section>
    <section class="edu-section edu-quiz-wrap"><div class="container edu-quiz"><div><p class="edu-eyebrow">Evaluación educativa</p><h2>Pon a prueba tus conocimientos</h2><p>No es una certificación; es una oportunidad para reconocer lo aprendido.</p></div><div id="quizCard" class="edu-quiz-card"></div></div></section>
    <section class="edu-section container" id="preguntas"><div class="edu-heading"><p class="edu-eyebrow">Respuestas breves</p><h2>Preguntas frecuentes</h2></div><div class="edu-faq">${D.faqs.map((f,i)=>`<article><h3><button aria-expanded="false" aria-controls="faq-${i}">${f[0]}<span>+</span></button></h3><div id="faq-${i}" hidden><p>${f[1]}</p></div></article>`).join('')}</div></section>
    <section class="edu-section container"><div class="edu-final"><p class="edu-eyebrow">Acompañamiento profesional</p><h2>El conocimiento es el primer paso. El acompañamiento correcto hace la diferencia.</h2><p>Habla con un agente de Diamantes Realty Group y recibe orientación según tu objetivo, presupuesto y tipo de propiedad.</p><div class="edu-actions"><a class="edu-btn edu-btn-primary" href="https://wa.me/50577265009?text=Hola%2C%20deseo%20hablar%20con%20un%20agente." target="_blank" rel="noopener noreferrer">Hablar con un agente</a><a class="edu-btn edu-btn-light" href="propiedades.html">Explorar propiedades</a><a class="edu-text-link" href="quieres-vender.html">Quiero vender mi propiedad</a></div></div><p class="edu-disclaimer">Este contenido es informativo y no sustituye la revisión de un abogado, notario, contador, valuador u otro profesional competente. Los requisitos y costos pueden variar según la propiedad, municipio y características de la operación.</p></section>
    <dialog id="guideModal" class="edu-modal"><button class="edu-modal-close" aria-label="Cerrar guía">×</button><div id="guideContent"></div></dialog>`;

  let activePath='comprar', activeLetter='all', query='';
  function renderPath(){const p=D.paths.find(x=>x.id===activePath); document.getElementById('path-panel').innerHTML=`<div>${icon(p.icon)}<p class="edu-eyebrow">Ruta seleccionada</p><h3>${p.title}</h3><p>${p.description}</p></div><ol>${p.modules.slice(0,5).map((m,i)=>`<li><span>${i+1}</span>${m.title||m}</li>`).join('')}</ol><a href="#${p.id==='comprar'?'compra':p.id==='vender'?'venta':p.id==='invertir'?'inversion':'documentos'}">Continuar esta ruta</a>`;}
  document.querySelectorAll('.edu-path').forEach(b=>b.onclick=()=>{activePath=b.dataset.path;document.querySelectorAll('.edu-path').forEach(x=>{const on=x===b;x.classList.toggle('is-active',on);x.setAttribute('aria-selected',on);x.querySelector('.edu-path-state').textContent=on?'Ruta activa':'Seleccionar'});renderPath()}); renderPath();
  function journey(el,data){let current=0;const draw=()=>{const s=data[current];el.innerHTML=`<div class="edu-step-tabs" role="tablist">${data.map((x,i)=>`<button role="tab" aria-selected="${i===current}" class="${i===current?'is-active':''}" data-i="${i}"><span>${i+1}</span>${x.title}</button>`).join('')}</div><article class="edu-step-detail" role="tabpanel"><p>Paso ${current+1} de ${data.length}</p><h3>${s.title}</h3><p>${s.text}</p><div><section><h4>Comprueba</h4><ul>${s.check.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h4>Evita</h4><p>${s.avoid}</p></section><section><h4>Acción recomendada</h4><p>${s.action}</p></section></div></article>`;el.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{current=+b.dataset.i;draw()})};draw()};
  journey(document.querySelector('[data-journey="buying"]'),D.buying); journey(document.querySelector('[data-journey="selling"]'),D.selling);
  const checks=[...document.querySelectorAll('[data-check]')];checks.forEach(c=>c.onchange=()=>{const n=checks.filter(x=>x.checked).length;document.getElementById('checkProgress').textContent=`${n} de ${checks.length} pasos preparados`;document.querySelector('.edu-progress span').style.width=`${n/checks.length*100}%`});
  document.getElementById('calculator').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),price=+f.get('price'),income=+f.get('income'),expenses=+f.get('expenses'),err=document.getElementById('calcError');if(!price||price<=0||income<0||expenses<0||!Number.isFinite(price+income+expenses)){err.textContent='Ingresa valores válidos; el precio debe ser mayor que cero.';return}err.textContent='';const annual=income*12, fmt=new Intl.NumberFormat('es-NI',{style:'currency',currency:f.get('currency')});document.getElementById('calcResults').innerHTML=`<span>Ingreso bruto anual<strong>${fmt.format(annual)}</strong></span><span>Rentabilidad bruta estimada<strong>${(annual/price*100).toFixed(2)} %</strong></span><span>Rentabilidad neta orientativa<strong>${((annual-expenses)/price*100).toFixed(2)} %</strong></span><small>Estimaciones educativas, sin conversiones de moneda.</small>`};
  function renderGloss(){const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const rows=D.glossary.filter(x=>(activeLetter==='all'||x.term[0]===activeLetter)&&norm(x.term+' '+x.definition).includes(norm(query)));document.getElementById('glossary').innerHTML=rows.map(x=>`<article><h3>${x.term}</h3><p>${x.definition}</p></article>`).join('');document.getElementById('glossEmpty').hidden=!!rows.length} document.getElementById('glossSearch').oninput=e=>{query=e.target.value;renderGloss()};document.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>{activeLetter=b.dataset.letter;document.querySelectorAll('[data-letter]').forEach(x=>x.classList.toggle('is-active',x===b));renderGloss()});renderGloss();
  document.querySelectorAll('.edu-myths button').forEach(b=>b.onclick=()=>{const d=b.nextElementSibling,open=d.hidden;d.hidden=!open;b.setAttribute('aria-expanded',open);b.textContent=open?'Ocultar realidad':'Ver realidad'});
  function mistakes(profile){document.getElementById('mistakes').innerHTML=D.mistakes[profile].map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${x}</li>`).join('')} mistakes('Compradores');document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-profile]').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-selected',x===b)});mistakes(b.dataset.profile)});
  const modal=document.getElementById('guideModal'),close=modal.querySelector('.edu-modal-close');let lastFocus;document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{lastFocus=b;const g=D.guides[b.dataset.guide];document.getElementById('guideContent').innerHTML=`<p class="edu-eyebrow">${g.category} · ${g.time}</p><h2>${g.title}</h2><p>${g.description}</p><ol>${g.body.map(x=>`<li>${x}</li>`).join('')}</ol><p class="edu-legal">Contenido general: adapta cada paso a la propiedad y obtén revisión profesional.</p>`;modal.showModal();close.focus()});const closeModal=()=>{modal.close();lastFocus?.focus()};close.onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
  document.querySelectorAll('.edu-faq button').forEach(b=>b.onclick=()=>{const d=b.closest('article').querySelector('div'),open=d.hidden;d.hidden=!open;b.setAttribute('aria-expanded',open);b.querySelector('span').textContent=open?'−':'+'});
  let qi=0,score=0,answered=false;const quiz=document.getElementById('quizCard');function drawQuiz(){if(qi===D.quiz.length){const msg=score>=5?'Buena base para tomar decisiones.':score>=3?'Vas por buen camino.':'Te recomendamos repasar algunos conceptos.';quiz.innerHTML=`<p class="edu-eyebrow">Resultado</p><h3>${score} de ${D.quiz.length} respuestas correctas</h3><p>${msg}</p><button class="edu-btn edu-btn-primary" id="retry">Intentar nuevamente</button>`;document.getElementById('retry').onclick=()=>{qi=score=0;drawQuiz()};return}answered=false;const q=D.quiz[qi];quiz.innerHTML=`<p>Pregunta ${qi+1} de ${D.quiz.length}</p><h3>${q.question}</h3><div class="edu-options">${q.options.map((x,i)=>`<button data-answer="${i}">${x}</button>`).join('')}</div><p id="quizFeedback" aria-live="polite"></p><button id="quizNext" class="edu-btn edu-btn-primary" disabled>${qi===D.quiz.length-1?'Ver resultado':'Siguiente pregunta'}</button>`;quiz.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const ok=+b.dataset.answer===q.answer;if(ok)score++;quiz.querySelectorAll('[data-answer]').forEach((x,i)=>{x.disabled=true;x.classList.toggle('is-correct',i===q.answer)});document.getElementById('quizFeedback').textContent=(ok?'Correcto. ':'Sigue aprendiendo. ')+q.feedback;document.getElementById('quizNext').disabled=false});document.getElementById('quizNext').onclick=()=>{qi++;drawQuiz()}}drawQuiz();
  const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:D.faqs.map(f=>({'@type':'Question',name:f[0],acceptedAnswer:{'@type':'Answer',text:f[1]}}))});document.head.append(schema);
  if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('edu-visible');o.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.edu-section').forEach(x=>{x.classList.add('edu-reveal');o.observe(x)})}
})();
