window.EDUCATION_CONTENT = (() => {
  const step = (title, text, check, avoid, action) => ({ title, text, check, avoid, action });
  const buying = [
    step('Definir necesidades y presupuesto','Aclara el uso, prioridades y recursos disponibles antes de buscar.',['Distinguir esenciales y deseables','Considerar gastos asociados'],'Buscar sin un rango realista.','Prepara una ficha de necesidades.'),
    step('Elegir ubicación','Compara accesos, servicios, entorno, seguridad percibida y planes personales.',['Visitar en horarios distintos','Revisar movilidad cotidiana'],'Decidir por una sola visita.','Selecciona tres zonas comparables.'),
    step('Comparar propiedades','Evalúa precio, estado, área, distribución y condiciones bajo los mismos criterios.',['Crear una matriz comparable','Registrar ventajas y pendientes'],'Comparar solo el precio publicado.','Solicita información completa.'),
    step('Revisar el estado físico','Observa estructura visible, instalaciones, humedad, ventilación y mantenimiento.',['Documentar hallazgos','Consultar a un técnico cuando aplique'],'Minimizar reparaciones futuras.','Realiza una visita técnica.'),
    step('Verificar documentación','Solicita una revisión profesional de titularidad, antecedentes y documentos aplicables.',['Identificar al propietario','Contrastar información registral'],'Entregar pagos sin revisión.','Coordina revisión legal independiente.'),
    step('Negociar condiciones','Define precio, forma de pago, entregas, inclusiones y condiciones de cierre.',['Dejar acuerdos por escrito','Aclarar responsabilidades'],'Negociar sin información de mercado.','Formula una oferta sustentada.'),
    step('Formalizar la compra','Documenta la operación y completa entrega e inscripciones con profesionales competentes.',['Revisar antes de firmar','Conservar soportes y comprobantes'],'Firmar documentos no comprendidos.','Solicita acompañamiento de cierre.')
  ];
  const selling = [
    step('Preparar la propiedad','Ordena, repara lo esencial y presenta cada espacio con claridad.',['Resolver mantenimiento visible','Despersonalizar ambientes'],'Publicar sin preparar.','Haz un recorrido crítico.'),
    step('Organizar documentación','Reúne los soportes disponibles para facilitar la revisión del caso.',['Identificación disponible','Documentación de dominio localizada'],'Esperar una oferta para buscar documentos.','Crea un expediente ordenado.'),
    step('Establecer precio de mercado','Analiza comparables, estado, ubicación y condiciones comerciales.',['Comparar propiedades relevantes','Definir margen de negociación'],'Fijar precio únicamente por emoción.','Solicita un análisis comercial.'),
    step('Preparar fotografías y publicidad','Construye una presentación precisa, atractiva y coherente.',['Espacios iluminados','Datos completos y verificables'],'Ocultar aspectos relevantes.','Prepara un plan de publicación.'),
    step('Filtrar compradores','Confirma interés, tiempos y capacidad de avanzar antes de coordinar.',['Registrar consultas','Proteger datos y seguridad'],'Aceptar visitas sin coordinación.','Define un protocolo de visitas.'),
    step('Negociar','Evalúa ofertas completas y no solamente la cifra principal.',['Revisar condiciones','Documentar contraofertas'],'Responder bajo presión.','Alinea límites antes de negociar.'),
    step('Formalizar el cierre','Coordina documentos, firma, pago y entrega de forma verificable.',['Confirmar hitos','Preparar acta de entrega'],'Entregar sin cumplir condiciones.','Trabaja con profesionales competentes.')
  ];
  const paths = [
    {id:'comprar',title:'Comprar una propiedad',description:'Del presupuesto al cierre, avanza con una revisión ordenada.',icon:'home',modules:buying},
    {id:'vender',title:'Vender una propiedad',description:'Prepara, posiciona y negocia tu inmueble con estrategia.',icon:'tag',modules:selling},
    {id:'invertir',title:'Invertir en bienes raíces',description:'Comprende rendimiento, costos, demanda, liquidez y riesgo.',icon:'chart',modules:['Ubicación','Plusvalía','Liquidez','Rentabilidad','Flujo de efectivo','Costos de mantenimiento','Demanda de alquiler','Riesgo','Horizonte de inversión','Diversificación']},
    {id:'documentos',title:'Documentos y procesos',description:'Conoce las etapas generales de revisión y formalización.',icon:'file',modules:['Reunir documentación','Realizar revisión legal','Acordar condiciones','Preparar instrumentos','Formalizar la operación','Inscripciones y entrega']}
  ];
  const glossary = [
    ['Área construida','Superficie correspondiente a las construcciones de una propiedad.'],['Área de terreno','Superficie total del lote o parcela.'],['Avalúo','Opinión técnica de valor elaborada según criterios y propósito definidos.'],['Catastro','Sistema de información física y administrativa de los inmuebles.'],['Cierre','Etapa en la que se completan las condiciones para formalizar y entregar.'],['Comisión inmobiliaria','Honorario acordado por servicios de intermediación inmobiliaria.'],['Contraoferta','Respuesta que propone condiciones diferentes a una oferta recibida.'],['Escritura pública','Instrumento autorizado por notario que documenta actos jurídicos.'],['Exclusividad','Acuerdo que encarga la comercialización bajo condiciones definidas.'],['Gravamen','Carga o limitación que puede afectar un inmueble y debe revisarse.'],['Liquidez','Facilidad relativa para convertir un activo en dinero sin afectar sustancialmente su valor.'],['Oferta','Propuesta de compra con precio y condiciones específicas.'],['Plusvalía','Variación positiva del valor de una propiedad a través del tiempo.'],['Promesa de venta','Acuerdo preparatorio sujeto a términos y condiciones pactados.'],['Registro','Institución y proceso de publicidad de derechos sobre inmuebles.'],['Rentabilidad','Relación entre los resultados de una inversión y los recursos destinados.']
  ].map(([term,definition])=>({term,definition}));
  return { paths, buying, selling, checklist:['Documentación disponible','Precio analizado','Propiedad ordenada','Fotografías preparadas','Información completa','Disponibilidad para visitas'], glossary,
    documents:['Identificación del propietario','Escritura de dominio','Antecedentes registrales','Libertad de gravamen','Solvencias','Plano o información catastral','Documentos municipales','Contrato de compraventa','Escritura pública','Inscripción registral','Documentación particular según el inmueble'],
    myths:[['El precio de publicación siempre es el valor real de mercado.','El valor debe analizarse con ubicación, estado, demanda, comparables y condiciones de la operación.'],['Cualquier mejora aumenta el valor en la misma proporción que costó.','El impacto depende de utilidad, calidad, demanda y expectativas del mercado.'],['Publicar en muchos lugares siempre vende más rápido.','La presentación, el precio, la estrategia y el seguimiento importan más que la cantidad de publicaciones.']],
    mistakes:{Compradores:['Comprar por impulso','No comparar','Ignorar costos adicionales','No revisar documentación','No inspeccionar la propiedad'],Vendedores:['Fijar el precio por emoción','Publicar información incompleta','Utilizar fotografías deficientes','No preparar documentos','No responder con rapidez'],Inversionistas:['Mirar solo el precio','Sobreestimar ingresos','Ignorar mantenimiento','No analizar demanda','No definir una estrategia de salida']},
    guides:[['Compra','Guía para comprar una casa','Organiza prioridades, visitas, comparación y cierre.','7 min'],['Compra','Guía para comprar un terreno','Revisa uso previsto, entorno, acceso e información documental.','6 min'],['Venta','Guía para vender una propiedad','Prepara el inmueble y una estrategia comercial clara.','8 min'],['Visitas','Guía para preparar una visita','Observa la propiedad con una lista de criterios útiles.','5 min'],['Documentos','Guía de documentos básicos','Comprende qué información suele revisarse según cada caso.','7 min'],['Inversión','Guía para analizar una inversión','Relaciona ingresos, gastos, demanda, horizonte y riesgo.','9 min']].map((g,i)=>({id:i,category:g[0],title:g[1],description:g[2],time:g[3],body:['Define tu objetivo antes de evaluar opciones.','Reúne información comparable y registra tus preguntas.','Solicita revisión de profesionales competentes cuando corresponda.','No realices pagos ni firmes documentos que no comprendas.']})),
    faqs:[['¿Qué debo revisar antes de comprar una propiedad?','Objetivo, presupuesto total, ubicación, estado físico, condiciones comerciales y documentación revisada por profesionales competentes.'],['¿Cómo se define el precio de venta?','Se analiza ubicación, estado, características, demanda, comparables relevantes y condiciones de la operación.'],['¿Qué es un avalúo?','Es una opinión técnica de valor preparada con un propósito y criterios definidos.'],['¿Qué documentos debo solicitar?','Depende del inmueble y del caso. Identificación, dominio, antecedentes, solvencias e información catastral suelen formar parte de la revisión profesional.'],['¿Por qué es importante revisar el registro?','Permite contrastar titularidad, antecedentes y posibles afectaciones antes de comprometerse.'],['¿Qué debo observar durante una visita?','Distribución, iluminación, ventilación, entorno, mantenimiento e instalaciones visibles.'],['¿Cómo puedo saber si una zona tiene potencial?','Analiza demanda, accesos, servicios, actividad económica, oferta y proyectos verificables.'],['¿Qué servicios ofrece un agente inmobiliario?','Puede orientar la búsqueda o comercialización, coordinar visitas, aportar análisis y acompañar la negociación y el proceso.'],['¿Cuándo es recomendable buscar asesoría legal?','Antes de firmar, entregar pagos o asumir obligaciones, y siempre que existan dudas sobre documentos o condiciones.'],['¿Cómo funciona la negociación de una propiedad?','Las partes intercambian propuestas sobre precio, pago, entrega y otras condiciones hasta acordarlas o cerrar la conversación.']],
    quiz:[['¿Qué debe analizarse además del precio?',['Solo el color','Ubicación, estado, costos y condiciones','Únicamente el tamaño'],1,'Una comparación integral reduce puntos ciegos.'],['¿Por qué revisar documentación?',['Para verificar información y riesgos','Para decorar el expediente','No es necesario'],0,'La revisión profesional protege la decisión.'],['¿Qué significa plusvalía?',['Un impuesto fijo','Una garantía','Variación positiva del valor en el tiempo'],2,'La plusvalía no está garantizada.'],['¿Qué gastos considerar al invertir?',['Solo compra','Operación, mantenimiento y administración','Ninguno'],1,'Los costos influyen en el resultado neto.'],['¿Qué hacer antes de fijar precio?',['Analizar mercado y comparables','Elegir una cifra emocional','Copiar cualquier anuncio'],0,'Un precio sustentado mejora la estrategia.'],['¿Qué hacer antes de firmar?',['Leer y obtener revisión competente','Firmar con rapidez','Confiar solo en mensajes'],0,'Comprender cada condición es esencial.']].map(([question,options,answer,feedback])=>({question,options,answer,feedback}))};
})();
